// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:kshk/core/api_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiKeys.firebaseKey,
    appId: '1:960470197223:web:b0b15c182c39ea492ad342',
    messagingSenderId: '960470197223',
    projectId: 'kshky-81dad',
    authDomain: 'kshky-81dad.firebaseapp.com',
    storageBucket: 'kshky-81dad.firebasestorage.app',
    measurementId: 'G-P9XL5DGPJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh5r0zF3sHM7liJC_Yz3aND7FMs7TFgpQ',
    appId: '1:960470197223:android:f70c3a46527e9e412ad342',
    messagingSenderId: '960470197223',
    projectId: 'kshky-81dad',
    storageBucket: 'kshky-81dad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQn4CP72dn-Q4ESu8iEC6IlrbZPAEf4jk',
    appId: '1:960470197223:ios:44ef22bdc165737c2ad342',
    messagingSenderId: '960470197223',
    projectId: 'kshky-81dad',
    storageBucket: 'kshky-81dad.firebasestorage.app',
    iosBundleId: 'com.example.kshk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQn4CP72dn-Q4ESu8iEC6IlrbZPAEf4jk',
    appId: '1:960470197223:ios:44ef22bdc165737c2ad342',
    messagingSenderId: '960470197223',
    projectId: 'kshky-81dad',
    storageBucket: 'kshky-81dad.firebasestorage.app',
    iosBundleId: 'com.example.kshk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCySmNOqsm0asUOZVw_DRVLUrdqmldhmrc',
    appId: '1:960470197223:web:e326ecb71a0288552ad342',
    messagingSenderId: '960470197223',
    projectId: 'kshky-81dad',
    authDomain: 'kshky-81dad.firebaseapp.com',
    storageBucket: 'kshky-81dad.firebasestorage.app',
    measurementId: 'G-QYT8WXQMCD',
  );
}
